In [6]:
import numpy as np
import pandas as pd
iris = pd.read_csv('Iris.csv')

In [13]:
# formating the dataset
x = iris.iloc[:,1:-1]
y = iris.iloc[:,-1]

In [14]:
# normalizing the dataset
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(x)

In [15]:
# split the dataset into train and test data
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.3)

In [19]:
# naive bayes using catogorical
from sklearn.naive_bayes import CategoricalNB
model=CategoricalNB()
model.fit(x_train,y_train)
predictions=model.predict(x_test)

# accuracy score, confusion matrix and classification report
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

0.9555555555555556
[[17  0  0]
 [ 0 15  0]
 [ 0  2 11]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       0.88      1.00      0.94        15
 Iris-virginica       1.00      0.85      0.92        13

       accuracy                           0.96        45
      macro avg       0.96      0.95      0.95        45
   weighted avg       0.96      0.96      0.96        45



In [21]:
# naive bayes using Bernoulli
from sklearn.naive_bayes import BernoulliNB
model = BernoulliNB()
model.fit(x_train,y_train)
predictions = model.predict(x_test)

# accuracy score, confusion matrix and classification report
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

0.28888888888888886
[[ 0  0 17]
 [ 0  0 15]
 [ 0  0 13]]
                 precision    recall  f1-score   support

    Iris-setosa       0.00      0.00      0.00        17
Iris-versicolor       0.00      0.00      0.00        15
 Iris-virginica       0.29      1.00      0.45        13

       accuracy                           0.29        45
      macro avg       0.10      0.33      0.15        45
   weighted avg       0.08      0.29      0.13        45



C:\Users\Aromal AS\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Aromal AS\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Aromal AS\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\metrics\_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_

In [33]:
# naive bayes using Gaussian
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
model.fit(x_train,y_train)
predictions = model.predict(x_test)

# accuracy score, confusion matrix and classification report
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
print(accuracy_score(y_test,predictions))
print(confusion_matrix(y_test,predictions))
print(classification_report(y_test,predictions))

0.9777777777777777
[[17  0  0]
 [ 0 15  0]
 [ 0  1 12]]
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        17
Iris-versicolor       0.94      1.00      0.97        15
 Iris-virginica       1.00      0.92      0.96        13

       accuracy                           0.98        45
      macro avg       0.98      0.97      0.98        45
   weighted avg       0.98      0.98      0.98        45

