In [2]:
import numpy as np
mylist = [1,2,3]
np.array(mylist)

array([1, 2, 3])

In [8]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
# array generated with in the range and 2 as step size
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [24]:
np.zeros(3)

array([0., 0., 0.])

In [34]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [39]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [48]:
np.linspace(0,100,6)

array([  0.,  20.,  40.,  60.,  80., 100.])

In [54]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [68]:
# methods for random number generation
np.random.rand(2)

array([0.08908198, 0.9989637 ])

In [75]:
np.random.randn(5,5)

array([[-1.41092695, -1.4942249 , -1.13869654, -0.14149084,  0.50007619],
       [ 1.38185308, -0.30058867,  1.96702997, -1.25733385,  0.09717103],
       [-0.88299342,  0.95659379,  0.16504307,  0.34269929,  0.08613701],
       [ 0.87691278,  0.50791919, -1.13557425,  0.35732167,  0.16426436],
       [-0.81620015, -0.19162295, -0.80616471, -0.67370147,  1.99529485]])

In [115]:
# generate a random number between the specified range
np.random.randint(0,10)

5

In [125]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [150]:
ranarr = np.random.randint(1,25,10)
ranarr

array([ 3, 13,  2, 22,  7, 22,  8,  9, 17, 13])

In [143]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [145]:
ranarr.max()

19

In [146]:
ranarr.min()

14

In [151]:
ranarr.argmax()

3

In [152]:
ranarr.argmin()

2

In [153]:
arr.shape

(25,)

In [156]:
# array indexing and slicing
ar = np.arange(0,11)
ar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [157]:
# indexing
ar[4]

4

In [159]:
# slicing
ar[1:9]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [162]:
# broadcasting :- to replace a particular or range of values in array.Broadcasting affect the original array!
a1 = np.arange(0,11)
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [163]:
a1[1] = 100
a1

array([  0, 100,   2,   3,   4,   5,   6,   7,   8,   9,  10])

In [166]:
a1[5:9] = 11
a1

array([  0, 100,   2,   3,   4,  11,  11,  11,  11,   9,  10])

In [169]:
a2 = np.arange(0,11)
slice_array = a2[3:8]
slice_array[:] = 99
a2

array([ 0,  1,  2, 99, 99, 99, 99, 99,  8,  9, 10])

In [171]:
arr_2d = np.array([ [5,10,15],[20,25,30],[35,40,45] ])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [172]:
arr_2d[1][2]

30

In [173]:
arr_2d[2][1]

40

In [176]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [177]:
arr_len = arr2d.shape[1]
arr_len

10

In [179]:
for i in range(arr_len):
    arr2d[i] = i
arr2d   

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [180]:
# fancy indexing
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [181]:
# conditional selection in array
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [182]:
bool_arr = arr>4
bool_arr

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [183]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [188]:
a11 = np.arange(1,11)
a11

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [189]:
# array addition
a11 + a11

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [190]:
# array substraction
a11 - a11

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [191]:
# array division
a11 / a11

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [192]:
1 / a11

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

In [14]:
a = np.arange(1000)
b = np.arange(1000)
dp = np.dot(a,b)
print(dp)
op = np.outer(a,b)
print(op)
ep = np.multiply(a,b)
print(ep)

332833500
[[     0      0      0 ...      0      0      0]
 [     0      1      2 ...    997    998    999]
 [     0      2      4 ...   1994   1996   1998]
 ...
 [     0    997   1994 ... 994009 995006 996003]
 [     0    998   1996 ... 995006 996004 997002]
 [     0    999   1998 ... 996003 997002 998001]]
[     0      1      4      9     16     25     36     49     64     81
    100    121    144    169    196    225    256    289    324    361
    400    441    484    529    576    625    676    729    784    841
    900    961   1024   1089   1156   1225   1296   1369   1444   1521
   1600   1681   1764   1849   1936   2025   2116   2209   2304   2401
   2500   2601   2704   2809   2916   3025   3136   3249   3364   3481
   3600   3721   3844   3969   4096   4225   4356   4489   4624   4761
   4900   5041   5184   5329   5476   5625   5776   5929   6084   6241
   6400   6561   6724   6889   7056   7225   7396   7569   7744   7921
   8100   8281   8464   8649   8836   9025   9216  